name: Merge to Main

on:
  push:
    branches:
      - main
    paths-ignore:
      - ".github/ISSUE_TEMPLATE/*"
      - "**.md"
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  NAME: nr-quickstart-helpers

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:
  deploys-test:
    name: TEST Deployments
    environment: test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        name: [backend, database, frontend, init]
        include:
          - name: backend
            overwrite: true
            file: backend/openshift.deploy.yml
          - name: database
            overwrite: false
            file: database/openshift.deploy.yml
          - name: frontend
            overwrite: true
            file: frontend/openshift.deploy.yml
          - name: init
            overwrite: false
            file: common/openshift.init.yml
    steps:
      - uses: bcgov-nr/action-deployer-openshift@v0.0.2
        with:
          file: ${{ matrix.file }}
          oc_namespace: ${{ secrets.OC_NAMESPACE }}
          oc_server: ${{ secrets.OC_SERVER }}
          oc_token: ${{ secrets.OC_TOKEN }}
          overwrite: ${{ matrix.overwrite }}
          parameters:
            -p ZONE=test -p PROMOTE=${{ github.repository }}/${{ matrix.name }}:test
            -p NAME=${{ github.event.repository.name }} ${{ matrix.parameters }}
          penetration_test: true
          repository: bcgov/nr-quickstart-typescript

  deploys-prod:
    name: PROD Deployments
    needs:
      - deploys-test
    environment: prod
    runs-on: ubuntu-latest
    strategy:
      matrix:
        name: [backend, database, frontend, init]
        include:
          - name: backend
            overwrite: true
            file: backend/openshift.deploy.yml
          - name: database
            overwrite: false
            file: database/openshift.deploy.yml
          - name: frontend
            overwrite: true
            file: frontend/openshift.deploy.yml
          - name: init
            overwrite: false
            file: common/openshift.init.yml
    steps:
      - uses: bcgov-nr/action-deployer-openshift@v0.0.2
        with:
          file: ${{ matrix.file }}
          oc_namespace: ${{ secrets.OC_NAMESPACE }}
          oc_server: ${{ secrets.OC_SERVER }}
          oc_token: ${{ secrets.OC_TOKEN }}
          overwrite: ${{ matrix.overwrite }}
          parameters:
            -p ZONE=prod -p PROMOTE=${{ github.repository }}/${{ matrix.name }}:test
            -p NAME=${{ github.event.repository.name }} ${{ matrix.parameters }}
          penetration_test: true
          repository: bcgov/nr-quickstart-typescript

  image-promotions:
    name: Promote images to PROD
    needs:
      - deploys-prod
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        package: [backend, database, frontend]
    steps:
      - uses: shrink/actions-docker-registry-tag@v3
        with:
          registry: ghcr.io
          repository: ${{ github.repository }}/${{ matrix.package }}
          target: test
          tags: prod
