name: Pull Request

on:
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  pr-greeting:
    name: PR Greeting
    env:
      DOMAIN: apps.silver.devops.gov.bc.ca
      NAME: nr-quickstart-helpers
    runs-on: ubuntu-22.04
    steps:
      - uses: DerekRoberts/action-pr-description-add@v0.0.2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          add_markdown: |
            ---

            Thanks for the PR!

            Any successful deployments (not always required) will be available below.
            [Backend](https://${{ env.NAME }}-${{ github.event.number }}-backend.${{ env.DOMAIN }}/) available
            [Frontend](https://${{ env.NAME }}-${{ github.event.number }}-frontend.${{ env.DOMAIN }}/) available

            Once merged, code will be promoted and handed off to following workflow run.
            [Main Merge Workflow](https://github.com/${{ github.repository }}/actions/workflows/merge-main.yml)

  secret-search:
    name: Secret Search
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: secret-search
        uses: Hacks4Snacks/secret-search@v1.1

  builds:
    # These builds don't have triggers and will fire every time
    name: Builds
    uses: ./.github/workflows/_build.yml
    strategy:
      matrix:
        component: [backend, database, frontend]
    secrets:
      gh_token: ${{ secrets.GITHUB_TOKEN }}
    with:
      component: ${{ matrix.component }}
      img_build: ${{ github.event.number }}
      img_fallback: test
      repository: bcgov/nr-quickstart-typescript

  deploys:
    name: Deploys
    needs:
      - builds
    # If any of the prerequs created a build, then deploy
    if: contains(needs.*.outputs.build, 'true')
    uses: ./.github/workflows/_deploy.yml
    strategy:
      matrix:
        component: [backend, database, frontend, init]
        include:
          - component: backend
            overwrite: true
            template_file: backend/openshift.deploy.yml
            template_vars: -p MIN_REPLICAS=1 -p MAX_REPLICAS=2
          - component: database
            overwrite: false
            template_file: database/openshift.deploy.yml
          - component: frontend
            overwrite: true
            template_file: frontend/openshift.deploy.yml
            template_vars: -p MIN_REPLICAS=1 -p MAX_REPLICAS=2
          - component: init
            overwrite: false
            template_file: common/openshift.init.yml
    secrets:
      oc_namespace: ${{ secrets.OC_NAMESPACE }}
      oc_server: ${{ secrets.OC_SERVER }}
      oc_token: ${{ secrets.OC_TOKEN }}
    with:
      component: ${{ matrix.component }}
      overwrite: ${{ matrix.overwrite }}
      repository: bcgov/nr-quickstart-typescript
      penetration_test: false
      template_file: ${{ matrix.template_file }}
      template_vars:
        -p ZONE=${{ github.event.number }} -p NAME=${{ github.event.repository.name }}
        -p PROMOTE=${{ github.repository }}/${{ matrix.component }}:${{ github.event.number }}
        ${{ matrix.template_vars }}
