name: Pull Request

on:
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  pr-greeting:
    name: PR Greeting
    env:
      DOMAIN: apps.silver.devops.gov.bc.ca
      NAME: nr-quickstart-helpers
    runs-on: ubuntu-22.04
    permissions:
      pull-requests: write
    steps:
      - uses: bcgov-nr/action-pr-description-add@v0.0.2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          add_markdown: |
            ---

            Thanks for the PR!

            Any successful deployments (not always required) will be available below.
            [Backend](https://${{ env.NAME }}-${{ github.event.number }}-backend.${{ env.DOMAIN }}/) available
            [Frontend](https://${{ env.NAME }}-${{ github.event.number }}-frontend.${{ env.DOMAIN }}/) available

            Once merged, code will be promoted and handed off to following workflow run.
            [Main Merge Workflow](https://github.com/${{ github.repository }}/actions/workflows/merge-main.bcgov-nr/action-deployer-openshift@v0.0.1)

  retags:
    # These builds don't have triggers and will fire every time
    name: Retags
    runs-on: ubuntu-latest
    permissions:
      packages: write
    strategy:
      matrix:
        package: [backend, database, frontend]
        include:
          - package: backend
            triggers: ('backend/')
          - package: database
            triggers: ('database/')
          - package: frontend
            triggers: ('frontend/')
    steps:
      - uses: actions/checkout@v3
      - uses: bcgov-nr/action-builder-ghcr@v1.1.0
        with:
          package: ${{ matrix.package }}
          tag: ${{ github.event.number }}
          tag_fallback: test
          repository: bcgov/nr-quickstart-typescript
          token: ${{ secrets.GITHUB_TOKEN }}
          triggers: ${{ matrix.triggers }}

  builds:
    # These builds don't have triggers and will fire every time
    name: Builds
    needs:
      - retags
    runs-on: ubuntu-latest
    permissions:
      packages: write
    strategy:
      matrix:
        package: [backend, database, frontend]
    steps:
      - uses: actions/checkout@v3
      - uses: bcgov-nr/action-builder-ghcr@v1.1.0
        with:
          package: ${{ matrix.package }}
          tag: ${{ github.event.number }}
          tag_fallback: test
          repository: bcgov/nr-quickstart-typescript
          token: ${{ secrets.GITHUB_TOKEN }}

  deploys:
    name: Deploys
    needs:
      - builds
    runs-on: ubuntu-latest
    strategy:
      matrix:
        name: [backend, database, frontend, init]
        include:
          - name: backend
            file: backend/openshift.deploy.yml
            overwrite: true
            parameters: -p MIN_REPLICAS=1 -p MAX_REPLICAS=2
          - name: database
            file: database/openshift.deploy.yml
            overwrite: false
          - name: frontend
            overwrite: true
            parameters: -p MIN_REPLICAS=1 -p MAX_REPLICAS=2
            file: frontend/openshift.deploy.yml
          - name: init
            overwrite: false
            file: common/openshift.init.yml
    steps:
      - uses: bcgov-nr/action-deployer-openshift@v0.1.0
        with:
          file: ${{ matrix.file }}
          oc_namespace: ${{ secrets.OC_NAMESPACE }}
          oc_server: ${{ secrets.OC_SERVER }}
          oc_token: ${{ secrets.OC_TOKEN }}
          overwrite: ${{ matrix.overwrite }}
          repository: bcgov/nr-quickstart-typescript
          penetration_test: false
          parameters:
            -p ZONE=${{ github.event.number }} -p NAME=${{ github.event.repository.name }}
            -p PROMOTE=${{ github.repository }}/${{ matrix.name }}:${{ github.event.number }}
            ${{ matrix.parameters }}
