name: Unit Tests and Analysis

on:
  pull_request:
  push:
    branches:
      - main
    paths-ignore:
      - ".github/**"
      - "**.md"
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  tests:
    name: Unit Tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dir: [backend, frontend]
        include:
          # Note: Don't use the same token twice!  This is a testing repo, not a live product
          - dir: backend
            token: SONAR_TOKEN
          - dir: frontend
            token: SONAR_TOKEN
    steps:
      - uses: actions/checkout@v3
      - uses: bcgov-nr/action-test-and-analyse@bug/missingPipe
        with:
          commands: |
            npm ci
            npm run test:cov
          dir: ${{ matrix.dir }}
          repository: bcgov/nr-quickstart-typescript
          sonar_args: |
            -Dsonar.exclusions=**/coverage/**,**/node_modules/**
            -Dsonar.organization=bcgov-nr
            -Dsonar.projectKey=bcgov_nr-quickstart-helpers
          sonar_comment_token: ${{ secrets.GITHUB_TOKEN }}
          sonar_project_token: ${{ secrets[matrix.token] }}
