name: Unit Tests and Analysis

on:
  pull_request:
  push:
    branches:
      - main
    paths-ignore:
      - ".github/**"
      - "**.md"
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  tests:
    name: Unit Tests
    uses: ./.github/workflows/_unit-tests.yml
    strategy:
      matrix:
        dir: [backend, frontend]
        include:
          - dir: backend
            sonar_projectKey: bcgov_nr-quickstart-helpers
          - dir: frontend
            sonar_projectKey: bcgov_nr-quickstart-helpers
    secrets:
      sonar_token: ${{ secrets.SONAR_TOKEN }}
    with:
      dir: ${{ matrix.dir }}
      repository: bcgov/nr-quickstart-typescript
      sonar_args: |
        -Dsonar.cobertura.reportPaths=coverage/cobertura-coverage.xml
        -Dsonar.exclusions=**/test/**,.github/**,**/migrations/**
        -Dsonar.javascript.lcov.reportPaths=coverage/lcov.info
        -Dsonar.organization=bcgov-sonarcloud
        -Dsonar.project.monorepo.enabled=true
        -Dsonar.projectKey=${{ matrix.sonar_projectKey }}
      test_cmd: |
        npm ci
        npm run test:cov
